/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Class.Feedback;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samurai
 */
public class TrainerFeedback extends javax.swing.JFrame {

    /**
     * Creates new form TrainerFeedback
     */
    public TrainerFeedback() {
        initComponents();
        bookTable.setAutoCreateRowSorter(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Trainer_Feedback = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Customer_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Trainer_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        returnbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        Cust_Paid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        importB = new javax.swing.JButton();
        updateB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Trainer_Feedback.setColumns(20);
        Trainer_Feedback.setRows(5);
        jScrollPane1.setViewportView(Trainer_Feedback);

        jLabel1.setText("Feedback");

        Customer_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_IDActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer ID");

        Trainer_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trainer_IDActionPerformed(evt);
            }
        });

        jLabel3.setText("Trainer ID");

        returnbutton.setText("< Return");
        returnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbuttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel4.setText("Trainer: collect payment & provide feedback ");

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Trainer ID", "Payment", "Feedback"
            }
        ));
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bookTable);

        Cust_Paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_PaidActionPerformed(evt);
            }
        });

        jLabel8.setText("Payment");

        importB.setText("Import");
        importB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBActionPerformed(evt);
            }
        });

        updateB.setText("Update");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        deleteB.setText("Delete");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(importB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cust_Paid, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Trainer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateB, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(deleteB, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Trainer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cust_Paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String CustomerID = Customer_ID.getText();
        String TrainerID = Trainer_ID.getText();
        String PaymentYN = Cust_Paid.getText();
        String TrainerFeedback = Trainer_Feedback.getText();
        Feedback f = new Feedback();
        int create = f.addFeedback(CustomerID, TrainerID, PaymentYN, TrainerFeedback);
        
        
        if(create == 1){
            JOptionPane.showMessageDialog(null,"Adding Feedback Was Successful!");
        }else if(create == 2){
            JOptionPane.showMessageDialog(this,
                    "Please fill up complete details.",
                    "Warning:",JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,
                    "Error\nPlease try again.",
                    "Warning:",JOptionPane.WARNING_MESSAGE);
           
        }
         Customer_ID.setText("");
         Trainer_ID.setText("");
         Cust_Paid.setText("");
         Trainer_Feedback.setText("");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Customer_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_IDActionPerformed

    private void Trainer_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trainer_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Trainer_IDActionPerformed

    private void returnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbuttonActionPerformed
        TrainerMenu main = new TrainerMenu();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnbuttonActionPerformed

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        DefaultTableModel tm = (DefaultTableModel)bookTable.getModel();

        String custid = tm.getValueAt(bookTable.getSelectedRow(), 0).toString();
        String trainerid = tm.getValueAt(bookTable.getSelectedRow(), 1).toString();
        String custyn = tm.getValueAt(bookTable.getSelectedRow(), 2).toString();
        String feedback = tm.getValueAt(bookTable.getSelectedRow(), 3).toString();

        

        Customer_ID.setText(custid);
        Trainer_ID.setText(trainerid);
        Cust_Paid.setText(custyn);
        Trainer_Feedback.setText(feedback);

        
        /*
        try {
            tdate = new SimpleDateFormat("dd-MM-yyyy").parse(trainDate);
        } catch (ParseException ex) {
            Logger.getLogger(ManagerManageBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        */

        /*
        trainerCmb1.removeAllItems();
        String[] arr = scanGoal(custgoal);
        for (String arr1 : arr) {
            trainerCmb1.addItem(arr1);
        }
        trainerCmb1.setSelectedItem(trainerid);*/

    }//GEN-LAST:event_bookTableMouseClicked

    private void Cust_PaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_PaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_PaidActionPerformed

    private void importBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBActionPerformed
        File fb = new File("Feedback.txt");
        try {
            FileReader fr = new FileReader(fb);
            BufferedReader br3 = new BufferedReader(fr);

            DefaultTableModel tm = (DefaultTableModel)bookTable.getModel();
            Object[] records = br3.lines().toArray();

            for (int i = 0; i < records.length; i++) {
                String[] row = records[i].toString().split(",");
                tm.addRow(row);
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this,
                "Oops, file not found.",
                "Warning:",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_importBActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        DefaultTableModel tm = (DefaultTableModel)bookTable.getModel();

        if(bookTable.getSelectedRowCount() == 1){
            String custid = Customer_ID.getText();
            String trainerid = Trainer_ID.getText();
            String custyn = Cust_Paid.getText();
            String feedback = Trainer_Feedback.getText();

        
            tm.setValueAt(custid,bookTable.getSelectedRow(),0);
            tm.setValueAt(trainerid,bookTable.getSelectedRow(),1);
            tm.setValueAt(custyn,bookTable.getSelectedRow(),2);
            tm.setValueAt(feedback,bookTable.getSelectedRow(),3);


            JOptionPane.showMessageDialog(this, "Update Successful!");

        }else if(bookTable.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(this, "The table is empty.\nPlease import.");
        }else{
            JOptionPane.showMessageDialog(this, "Please select a record to modify~");
        }
    }//GEN-LAST:event_updateBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        DefaultTableModel tm = (DefaultTableModel)bookTable.getModel();

        if(bookTable.getSelectedRowCount() == 1){
            tm.removeRow(bookTable.getSelectedRow());
        }
        else{
            if(bookTable.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "The table is empty.\nPlease import.");
            }
            else{
                JOptionPane.showMessageDialog(this,
                    "Please select single row for delete","Warning:",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainerFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainerFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainerFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainerFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainerFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cust_Paid;
    private javax.swing.JTextField Customer_ID;
    private javax.swing.JTextArea Trainer_Feedback;
    private javax.swing.JTextField Trainer_ID;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton deleteB;
    private javax.swing.JButton importB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton returnbutton;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
