/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Class.Booking;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samurai
 */
public class TrainerCheckSession extends javax.swing.JFrame {

    /**
     * Creates new form TrainerCheckSession
     */
    public TrainerCheckSession() {
        initComponents();
        
//https://stackoverflow.com/questions/22416647/how-to-get-the-center-x-and-y-of-desktop-with-swing

        Toolkit tk = this.getToolkit();
        Dimension dim = tk.getScreenSize();
        int x = (int) dim.getWidth() / 2 - this.getWidth() / 2;
        int y = (int) dim.getHeight() / 2 - this.getHeight() / 2;
        this.setLocation(x, y);
        setTitle("Trainer: Check Sessions");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImportSession = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        returnbutton = new javax.swing.JButton();
        Trainer_ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exportB1 = new javax.swing.JButton();
        ImportSession1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImportSession.setText("Search");
        ImportSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportSessionActionPerformed(evt);
            }
        });

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Goal", "Trainer ID", "Training Date", "Starting Time", "Duration", "Ending TIme", "Amount"
            }
        ));
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);

        returnbutton.setText("< Return");
        returnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbuttonActionPerformed(evt);
            }
        });

        Trainer_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trainer_IDActionPerformed(evt);
            }
        });

        jLabel1.setText("Filter by Trainer ID");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setText("Trainer Check Sessions");

        exportB1.setText("Export");
        exportB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportB1ActionPerformed(evt);
            }
        });

        ImportSession1.setText("Import");
        ImportSession1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportSession1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(returnbutton)
                                .addGap(177, 177, 177)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(Trainer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ImportSession, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exportB1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImportSession1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(returnbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(41, Short.MAX_VALUE)
                        .addComponent(ImportSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(Trainer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ImportSession, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(exportB1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImportSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportSessionActionPerformed
        File fb = new File("Booking.txt");
        try {
            FileReader fr = new FileReader(fb);
            BufferedReader br3 = new BufferedReader(fr);

            DefaultTableModel tm = (DefaultTableModel) bookTable.getModel();
            
            tm.setRowCount(0); //this set the row to zero to avoid duplication of records
            Object[] records = br3.lines().toArray();

            String trainerId = Trainer_ID.getText();
            for (int i = 0; i < records.length; i++) {
                String[] row = records[i].toString().split(",");

                if (row[3].equals(trainerId))  {
                    tm.addRow(row);
                }

            }

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this,
                    "Oops, file not found.",
                    "Warning:", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ImportSessionActionPerformed

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        DefaultTableModel tm = (DefaultTableModel)bookTable.getModel();

        String bookid = tm.getValueAt(bookTable.getSelectedRow(),0).toString();
        String custid = tm.getValueAt(bookTable.getSelectedRow(),1).toString();
        String custgoal = tm.getValueAt(bookTable.getSelectedRow(),2).toString();
        String trainerid = tm.getValueAt(bookTable.getSelectedRow(),3).toString();
        String trainDate = tm.getValueAt(bookTable.getSelectedRow(),4).toString();
        String startT = tm.getValueAt(bookTable.getSelectedRow(),5).toString();
        String duration = tm.getValueAt(bookTable.getSelectedRow(),6).toString();
        String endT = tm.getValueAt(bookTable.getSelectedRow(),7).toString();
        String amount = tm.getValueAt(bookTable.getSelectedRow(),8).toString();

        

    }//GEN-LAST:event_bookTableMouseClicked

    private void returnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbuttonActionPerformed
        TrainerMenu main = new TrainerMenu();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnbuttonActionPerformed

    private void Trainer_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trainer_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Trainer_IDActionPerformed

    private void exportB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportB1ActionPerformed
        Booking b = new Booking();
        int export = 0;
        File f = new File("Booking.txt");
        try{
            FileWriter fw = new FileWriter(f);
            BufferedWriter bw = new BufferedWriter(fw);

            for (int i = 0; i < bookTable.getRowCount(); i++) {
                for (int j = 0; j < bookTable.getColumnCount(); j++) {
                    bw.write(bookTable.getModel().getValueAt(i,j).toString()+",");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
            export = 1;
        } catch (IOException ex) {
            Logger.getLogger(ManagerManageBooking.class.getName()).log(Level.SEVERE, null, ex);
            export = 2;
        }

        b.manage(export);
    }//GEN-LAST:event_exportB1ActionPerformed

    private void ImportSession1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportSession1ActionPerformed
        File fb = new File("Booking.txt");
        try {
            FileReader fr = new FileReader(fb);
            BufferedReader br3 = new BufferedReader(fr);

            DefaultTableModel tm = (DefaultTableModel) bookTable.getModel();
            Object[] records = br3.lines().toArray();

            for (int i = 0; i < records.length; i++) {
                String[] row = records[i].toString().split(",");
                tm.addRow(row);
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this,
                    "Oops, file not found.",
                    "Warning:", JOptionPane.WARNING_MESSAGE);
        }
     }//GEN-LAST:event_ImportSession1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainerCheckSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainerCheckSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainerCheckSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainerCheckSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainerCheckSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImportSession;
    private javax.swing.JButton ImportSession1;
    private javax.swing.JTextField Trainer_ID;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton exportB1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnbutton;
    // End of variables declaration//GEN-END:variables
}
